export enum VenueStatus {
  DRAFT = 'DRAFT',

  PENDING_AVAILABILITY = 'PENDING_AVAILABILITY',

  PENDING_BOOKING = 'PENDING_BOOKING',

  CANCELED = 'CANCELED',

  SCHEDULED = 'SCHEDULED',

  PENDING_PAYMENT = 'PENDING_PAYMENT',

  PAYED = 'PAYED',

  CLOSED = 'CLOSED',
}
